apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-extraction
  namespace: django-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-extraction
  template:
    metadata:
      labels:
        app: django-extraction
    spec:
      initContainers:
      - name: migrate
        image: us-central1-docker.pkg.dev/testing-472102/extraction-repo/django-extraction:latest
        imagePullPolicy: Always
        command: ["python", "manage.py", "migrate", "--noinput"]
        envFrom:
        - configMapRef:
            name: django-config
        - secretRef:
            name: django-secret
      containers:
      - name: django
        image: us-central1-docker.pkg.dev/testing-472102/extraction-repo/django-extraction:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: django-config
        - secretRef:
            name: django-secret
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
