apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: django-gke
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: django-extraction

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: django-gke
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
